Program 	= Item* EOF
Item 		= Handler / Function / Alias
Handler 	= 'on' EventKind ':' ( TextRegex ':' ( ContextRegex ':' )? )? Block
Function 	= 'fn' id ':' ( TextRegex ':' )* Block
Alias 		= 'alias' id ':' ( TextRegex ':' )* Block
Block		= '{' Stmt? ( ( '|' / r'\r?\n' ) Stmt )* '}' r'\r?\n'
Stmt 		= Declare / DeclareAssign / Assign / Expr / If / While / For / Break / Continue / Return
Declare 	= 'set' var
DeclareAssign	= 'set' var AssignOp Expr
Expr 		= '$null' / bool / int / float / str / idx / call / list / map / id / idt / Unary / Binary / Ternary / Logical / TextRegex
bool 		= r'true|false'
int 		= r'-?0|([1-9][0-9]*)'
float		= r'-?(0|([1-9][0-9]*))\.([0-9]+)'
str		= r'\"([^]*)\"'
idx 		= call '.' id
call		= idt '(' Expr? ( ',' Expr )* ')'
list		= '[' Expr? ( ',' Expr )* ']'
map		= idt '.' id AssignOp Expr
Unary		= '!' Expr
Binary		= Expr ( '+' / '-' / '*' / '/' / '^' / '%%' / '++' / '==' / '!=' / '>=' / '<=' / '>' / '<' ) Expr
var		= idv ( '('? '$+' ( id / idt / idv ) '$+'? ')'? )*
id		= r'[a-zA-Z_][a-zA-Z0-9_]*'
idt 		= r'\$[a-zA-Z_][a-zA-Z0-9_]*'
idv		= r'\%[a-zA-Z_][a-zA-Z0-9_]*'


